vim.g.silicon = {
    output = '~/Screenshots/silicon-{time:%Y-%m-%d-%H%M%S}.png',
    theme =                 '1337',
    font =                  'Hack',
    background =            '#AAAAFF',
--    shadow-color =          '#555555',
--    line-pad =              2,
--    pad-horiz =             80,
--    pad-vert =              100,
--    shadow-blur-radius =    0,
--    shadow-offset-x =       0,
--    shadow-offset-y =       0,
--    line-number =           true,
--    round-corner =          true,
--    window-controls =       true,
}
